### ISSUE TITLE
Question: How do we send SQL queries?

### ISSUE THREAD

**Issue by dkullmann** [Microsoft/AppInsights-Ruby#11]
@jngli hello, do you know how we can send an SQL query?

I see the telemetry type is a metric, but I don't know what the custom properties are that should be included.

**Comment by jngli** [comment]
There are multiple telemetry types as defined in the contract classes, all of them support properties which are custom defined, that is, you define the property and responsible for tracking its value.

**Comment by dkullmann** [comment]
@jngli thank you, we'll try sending SQL data using [this](https://github.com/Microsoft/AppInsights-Ruby/blob/73df1c367ba42da2c9ecdc30800695df3db8eb50/lib/application_insights/channel/contracts/dependency_kind.rb#L18) and setting it to `3`

Our goal is to make sure the SQL metrics show up here:
![image](https://cloud.githubusercontent.com/assets/422899/6420393/b17443fe-be93-11e4-8ddf-b6601f945c90.png)

We also weren't sure if SQL metrics could include SQL-specific things like Time + Query (we can include them as custom properties.)

**Comment by jngli** [comment]
The rdd (RemoteDependencyData) is not officially supported by Ruby SDK yet, not exposed directly via TelemetryClient. You could manually create an rdd and send to AI using the telemetry channel, what you've done I think.  However there are two issues while processing rdd:

1. The dependency kind is not processed correctly and got addressed recently with a schema change but not updated in Ruby SDK yet.
2. The rdd would be ignored if ai.device.id is not specified which would be fixed in the server side in the near future.

You can work around the above issues with following changes:
1. rdd.dependency_kind = 0   # SQL should be set to 0
2. tc.context.device.id = "1"   # explicitly set device id

What do you mean by 'Time', the time stamp making the sql query, execution time, or something else?  For query, yes, you can use the custom property to track it.

Thanks,
Jing

**Comment by dkullmann** [comment]
@jngli exactly — the SQL query execution time.

Thank for all the other info, btw.

**Comment by jngli** [comment]
The 'value' field is supposed to use for tracking execution time (i.e., dependency duration used in UI).

**Comment by dkullmann** [comment]
@jngli ok perfect, thank you!

**Comment by jngli** [comment]
@dkullmann the sdk is updated with latest schema where the dependency kind issue should be fixed.
