### ISSUE TITLE
Refactor Contracts

### ISSUE THREAD

**Issue by emancu** [Microsoft/AppInsights-Ruby#6]
I know there is not too much logic in this objects, actually they are very simple. The thing is the objects are simpler than the code written and I have a refactor in mind that will help a lot to the simplicity and easiness of code maintenance.

I don't know if you are already working on a refactor of those objects, but I'll try to send a PR tonight so I can start contributing to this gem and you can start reviewing it. I'll be looking forward to see your feedback on the PR.

Also, I'm available to pair program with any of you if you think it is necessary.

**Comment by jngli** [comment]
The contract classes look more complex than they should be as it is written in a way so that it can be auto-generated from telemetry schema, so that no manual change incurred when schema evolves.   The contract tests are auto-generated as well.  It could be simplified in another way while still be able to regenerate.  Looking forward to your PR.

**Comment by emancu** [comment]
Since the tests are auto-generated, I won't refactor them.
On the other hand, the changes that I proposed keep the simplicity and is easy to extract a template for auto-generated files.

Hope you like the changes =)

**Comment by jngli** [comment]
The change has merged back to develop branch.  I'll update the generator to include these changes.
